version: '3'

vars:
  OVERNIGHT: swebster/overnight
  PODLET: ghcr.io/containers/podlet:v0.3.0
  IMAGE_FORMAT: '{{`{{.Repository}}:{{.Tag}}`}}'
  IMAGE_OPTIONS: --filter dangling=false --format {{.IMAGE_FORMAT}}
  PODMAN_OPTIONS_FILE: .task/podman_run.options
  SERVICE_CONFIG_FILE: .task/overnight.container

run: when_changed

tasks:
  config:local:
    desc: Create a config file for custom settings
    cmds:
      - ./configure_local.sh
    interactive: true
    sources:
      - configure_local.sh
    generates:
      - .env.local

  config:secrets:
    desc: Create a config file for sensitive data
    cmds:
      - ./configure_secrets.sh
    interactive: true
    sources:
      - configure_secrets.sh
    generates:
      - .env.secrets

  config:podman:
    desc: Generate common 'podman run' options
    deps: [config:local]
    cmds:
      - ./extract_env.sh
    interactive: true
    sources:
      - .env.local
      - .env.secrets.template
      - extract_env.sh
    generates:
      - '{{.PODMAN_OPTIONS_FILE}}'

  podman:build:
    desc: Build the relevant container image
    vars:
      TARGET: 'localhost/{{.OVERNIGHT}}:latest'
    cmds:
      - podman build . -t {{.OVERNIGHT}}
    sources:
      - Gemfile*
      - bin/overnight
      - lib/**/*.rb
      - overnight.gemspec
    status:
      - podman images {{.IMAGE_OPTIONS}} | grep -qx {{.TARGET}}

  podman:secrets:
    desc: Store sensitive config data appropriately
    deps: [config:secrets]
    vars:
      MISSING_SECRETS:
        sh: >
          awk -F= '{print tolower($1)}' .env.secrets.template |
            xargs -I{} sh -c 'podman secret exists {} || printf "%s\n" {}'
    cmds:
      - for: { var: MISSING_SECRETS }
        cmd: >
          grep -iq {{.ITEM}} .env.secrets &&
          awk -F= '$1 == "{{upper .ITEM}}" {printf("%s", $2)}' .env.secrets |
            podman secret create {{.ITEM}} -
    status:
      - test {{len .MISSING_SECRETS}} -eq 0

  podman:run:internal:
    deps: [podman:secrets, podman:build]
    vars:
      RUN_OPTIONS:
        sh: paste -s -d ' ' {{.PODMAN_OPTIONS_FILE}}
      TARGET: 'localhost/{{.OVERNIGHT}}:latest'
    cmds:
      - podman run -it --rm {{.RUN_OPTIONS}} {{.OVERNIGHT}} {{.CLI_ARGS}}
    status:
      - podman ps --format '{{`{{.Image}}`}}' | grep -qx {{.TARGET}}

  podman:run:
    desc: Run overnight in a container
    deps: [config:podman]
    cmds:
      - task: podman:run:internal

  podlet:pull:
    desc: Pull a container image for running podlet
    internal: true
    cmds:
      - podman pull {{.PODLET}}
    status:
      - podman images {{.IMAGE_OPTIONS}} | grep -qx {{.PODLET}}

  podlet:run:internal:
    internal: true
    deps: [podlet:pull]
    vars:
      RUN_OPTIONS:
        sh: paste -s -d ' ' {{.PODMAN_OPTIONS_FILE}}
    cmds:
      - |
        podman run --rm {{.PODLET}} --install \
          podman run --restart=always {{.RUN_OPTIONS}} {{.OVERNIGHT}} |
          grep -v '^#' > {{.SERVICE_CONFIG_FILE}}
    sources:
      - '{{.PODMAN_OPTIONS_FILE}}'
    generates:
      - '{{.SERVICE_CONFIG_FILE}}'

  podlet:run:
    desc: Generate configuration to run overnight as a systemd service
    deps: [config:podman]
    cmds:
      - task: podlet:run:internal
