version: '3'

vars:
  IMAGE_NAME: swebster/overnight

run: when_changed

tasks:
  config:local:
    desc: Create a config file for custom settings
    cmds:
      - ./configure_local.sh
    interactive: true
    sources:
      - configure_local.sh
    generates:
      - .env.local

  config:secrets:
    desc: Create a config file for sensitive data
    cmds:
      - ./configure_secrets.sh
    interactive: true
    sources:
      - configure_secrets.sh
    generates:
      - .env.secrets

  podman:build:
    vars:
      IMAGE_FORMAT: '{{`{{.Repository}}:{{.Tag}}`}}'
      TARGET: 'localhost/{{.IMAGE_NAME}}:latest'
    cmds:
      - podman build . -t {{.IMAGE_NAME}}
    sources:
      - Gemfile*
      - bin/overnight
      - lib/**/*.rb
      - overnight.gemspec
    status:
      - podman images --filter dangling=false --format {{.IMAGE_FORMAT}} | grep -qx {{.TARGET}}

  podman:run:
    deps: [config:local, config:secrets, podman:build]
    cmds:
      - podman run -it --rm --env-file .env.local --env-file .env.secrets {{.IMAGE_NAME}}
